
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import ScrollManager from "./utils/scroll-manager";

export const metadata: Metadata = {
  title: "Simona Maleti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="it">
      <body>
        <ScrollManager />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
